#+TITLE: org-jmpress-js.el
#+SUBTITLE: minimalistic org-mode backend for jmpress.js
#+AUTHOR: François-David Collin
#+OPTIONS: toc:1 num:nil
#+JMPRESSJS_STYLE: css/simple.css
#+JMPRESSJQ_SRC: js/jquery/jquery.min.js
#+JMPRESSJS_SRC: js/jmpress/jmpress.js
#+JMPRESSUSER_SRC: simple.js
* WHAT'S THIS?
  This library implements a minimalistic jmpress.js back-end for Org
  generic exporter based on ox-html.el.

  http://fradav.github.io/org-jmpress-js.el/ is a demo page.

  * See http://orgmode.org/ about Org-mode.
  * See http://jmpressjs.github.io/jmpress.js/ about jmpress.js.

  This work is mostly based on kinjo's own impress.js org-mode
  backend.

  This has been tested on latest org-mode (git version)

* INSTALLATION
  1. First of all, let's make sure about your Org-mode version.
     This library has been tested on 8.3x.
     #+BEGIN_SRC text
       M-x org-version
     #+END_SRC
  2. Get org-jmpress-js.el. For example,
     #+BEGIN_SRC sh
       git clone https://github.com/fradav/org-jmpress-js.el.git
     #+END_SRC
  3. Add load-path in your init.el and restart the emacs.
     #+BEGIN_SRC emacs-lisp
       (add-to-list 'load-path "~/org-jmpress-js.el")
       (require 'ox-jmpress-js)
     #+END_SRC

* INSTALLATION Part two
  1. Install node-kit
  2. Install Bower-installer
     #+BEGIN_SRC sh
       npm install -g bower-installer
     #+END_SRC
  3. Install jQuery and jmpress
     #+BEGIN_SRC sh
       bower-installer
     #+END_SRC

* USAGE
  1. Open README.org in your emacs.
  2. To export to jmpress.js HTML file, type =C-c= =C-e=.
  3. =*Org Export Dispatcher*= buffer will open.
     Hit =J= key 2 times, then README.html will be exported.
  4. Open exported file in your web browser.

* EXPORT OPTIONS
  Following special export options are available.
  * =#+JMPRESSJS_STYLE=
    A URL or filepath to jmpress.js's CSS file.

  * =#+JMPRESSJQ_SRC=
    A URL or filepath to jQuery.

  * =#+JMPRESSJS_SRC=
    A URL or filepath to jmpress.js.

  * =#+JMPRESSUSER_SRC=
    A URL or filepath to user script.

* MOTIVATIONS
  - As org-mode is always in motion, an org-html derived backend like
    =org-jmpress-js.el= is somewhat problematic in mid/long term,
    because of broken dependencies.
  - The fact that =jmpress.js= already
    use =jQuery= should allow us to centralize all the presentation
    magics in the javascript side.
  - That's why the elisp file almost does nothing except adding the
    specific js and css files to a vanilla org-html generated file.

* GUIDELINES
  The user script should contain three parts (see =simple.js= for
  example):
  - DOM reorganisation :: like title, postamble placement, id
       generation
  - Class style application :: where the =step= and/or =slide= classes
       should be applied, for example
  - Jmpress specific calls :: like template applications, and finally
       the mandatory =.jmpress()= call
* LICENSE
  Licensed under the GPLv2 license.

